// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"week04/internal/biz"
	"week04/internal/data"
	"week04/internal/service"
)

// Injectors from wire.go:

func InitProjectDemo() *biz.ProjectDemoHandler {
	projectDemoDao := data.NewProjectDao()
	projectDemoService := service.NewProjectDemoService(projectDemoDao)
	projectDemoHandler := biz.NewProjectDemoHandler(projectDemoService)
	return projectDemoHandler
}
